#!/bin/tcsh
#SBATCH -o ./outputs/Gmazes32-results.txt
#SBATCH --account=def-nathanst-ab
#SBATCH --gpus-per-node=3
#SBATCH --time=24:00:00

foreach scen (./scenarios/mazes/*-32-*.scen)

#foreach alg (`seq 0 6`)
set alg = `echo 7`

foreach weight ( 1.25 1.5 2.0 3.0 5.0 9.0 )

set x = `echo $scen | sed 's/.*\///g'`
set map = `echo $x | sed 's/.scen//'`
echo "ALG " $alg " weight " $weight " map " $map

./bin/release/DSDWA -map ./maps/mazes/$map $scen $alg $weight

end
end
