#!/bin/tcsh
#SBATCH -o ./outputs/dao-results.txt
#SBATCH --account=def-nathanst-ab
#SBATCH --time=24:00:00

foreach scen (./scenarios/dao/*.map.scen)

foreach alg (`seq 0 6`)

foreach weight ( 1.25 1.5 2.0 3.0 5.0 9.0 )

set x = `echo $scen | sed 's/.*\///g'`
set map = `echo $x | sed 's/.scen//'`
echo "ALG " $alg " weight " $weight " map " $map

./bin/release/DSDWA -map ./maps/dao/$map $scen $alg $weight

end
end
end
