#!/bin/tcsh

foreach problem (`seq 81 82`)

echo "------------------"
echo "problem number" $problem

foreach alg (`seq 0 3`)

echo "algorithm" $alg

#foreach weight ( 1.0 1.001 1.005 1.01 1.05 1.1 1.15 1.2 1.3 1.5 1.75 2.0 2.52 3.0 )
foreach weight ( 3.0 4.0 5.0 6.0 7.0 8.0 )

echo "with weight" $weight

./bin/release/DSDWA -stp $problem $alg $weight >> results81.txt

end

end

end

mv results81.txt ./papers/DSDWA

python3 ./papers/DSDWA/makeTable.py 4 5
